name: Wakatime Code Stats

on:
  workflow_dispatch:
  watch:
    branches: [ main ]
  schedule:
    - cron: '30 5 * * *'

jobs:
  update-Readme:
    name: Automatically update my README  
    runs-on: ubuntu-latest
    steps:
      - uses: tariksahni/coding-stats-wakatime@v1.0.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
